openapi: 3.0.0
info:
  title: Fab
  version: 1.0.0
  description: ''
servers:
  - url: https://api.applicationinsights.io
paths:
  /v1/apps/d424c29f-e3dd-498b-a118-3014eaec0a11/query:
    get:
      summary: AppInsight
      parameters:
        - name: query
          in: query
          schema:
            type: string
          example: requests | take 10
        - name: timespan
          in: query
          schema:
            type: string
          example: PT12H
        - name: x-api-key
          in: header
          schema:
            type: string
          example: 8rj27ga5nmad8e4f4lesg02kvpb0gidy6icz1sho
      responses: 
        "200":
          description: Successful query response.
